### ISSUE TITLE
Stories 

### ISSUE THREAD

**Issue by DannMcC** [tiy-tpa-fee/campfire#14]
This is the story component that will be imported into each page that lists the stories. Stories should have a thumbnail image, title, author (person who posted, not person who wrote), short description, and the tags. The information should be displayed vertically first. Once it is displayed vertically, create a second component that is horizontal. If you need clarification, ask Dan.

**Comment by DannMcC** [comment]
Also, the story need to have the number of up votes

**Comment by cfsanderson** [comment]
I'm trying to think through how images will be handled. They could be coming from the backend in various dimensions/sizes and we'll need to display the same image in lots of different scenarios (staff picks, front-end category, top story, etc.) but they can't be stretched or look too weird. Maybe a topic for discussion.
